### ISSUE TITLE
operator-courier treats .git dir as a package

### ISSUE THREAD

**Issue by dmitri-d** [operator-framework/operator-courier#124]
Which results in an error:

```
INFO:root:Parsing version: .git
INFO:operatorcourier.validate:Validating bundle.
ERROR:operatorcourier.validate:Bundle does not contain any clusterServiceVersions.
INFO:operatorcourier.validate:Validating packages.

```

Probably should skip all directories starting with a dot.

**Comment by kevinrizza** [comment]
This should resolved by https://github.com/operator-framework/operator-courier/pull/122, which will ignore any extra unrelated folders when attempting to validate or push.

**Comment by kevinrizza** [comment]
Fixed in the latest release: https://github.com/operator-framework/operator-courier/releases/tag/v2.0.3
