### ISSUE TITLE
Please include LICENSE, docs, command, and tests in pypi tarball.

### ISSUE THREAD

**Issue by ralphbean** [operator-framework/operator-courier#13]
I'm trying to package operator-courier for Fedora.

The LICENSE file should be distributed with the tarball since the license is *for* users, they should find it with the tarball they pull down from pypi.  This is a must-have.

The tests would be nice, so I can re-run them in the Fedora buildsystem when building the rpm.

The docs, also - since they're for users, so they show up in `/usr/share/`.

**Comment by ralphbean** [comment]
You can usually add a file to the root of your repo called `MANIFEST.in` that will tell setuptools about additional folders and files to include in your 1.0.1 release.

**Comment by kevinrizza** [comment]
This was fixed by https://github.com/operator-framework/operator-courier/commit/122925328657f56ffef0ff5c8e3900829c66a0f2
