### ISSUE TITLE
operator courier don't validate all customresourcedefinitions required fields

### ISSUE THREAD

**Issue by ssimk0** [operator-framework/operator-courier#136]
Hi,
I validating operator with courier `operator-courier verify --ui_validate_io path` which don't have fields: 
- `spec.customresourcedefinitions.owned.displayName`
- `spec.customresourcedefinitions.owned.description`

but this field is required by olm, when I try apply the CSV without these I get error:
`
spec.customresourcedefinitions.owned.displayName in body is required
spec.customresourcedefinitions.owned.description in body is required
`

**Comment by jsm84** [comment]
+1 on this. I had a partner fail in the certification pipeline who was missing these same two fields, and the metadata passed `operator-courier verify --ui_validate_io` with no errors or warnings.
