### ISSUE TITLE
exit code not set correctly if validation fails

### ISSUE THREAD

**Issue by scoheb** [operator-framework/operator-courier#15]
`[root@0d92433c567b test]# operator-courier verify .`
`csv metadata.annotations not defined.`
`csv spec.icon not defined`
`[root@0d92433c567b test]# echo $?`
`0`

**Comment by SamiSousa** [comment]
I believe in this case the output is warning that some recommended fields are empty. This isn't an error and verification passes since the CSV is valid.

**Comment by scoheb** [comment]
That makes sense. 
It may be more helpful if each warning is prefixed with `WARNING: `

**Comment by kevinrizza** [comment]
This issue is resolved by https://github.com/operator-framework/operator-courier/commit/477ecbc0eb4d00fbbf3b7c6dc5785d521e67be69
