### ISSUE TITLE
Is this project active

### ISSUE THREAD

**Issue by hassenius** [operator-framework/operator-courier#186]
We currently have a CICD process to build a catalog that contains a number of operators and operands. The pipeline is built in python, so this project appears to provide a nice set of modules and functions that we can use for validation of CSVs before bringing them into our catalog.
However, it's unclear from the activity level this year if this project is being actively maintained, and if it's a good strategic direction for us to go.

@kevinrizza any thoughts?

**Comment by kevinrizza** [comment]
@hassenius All the maintainers of this project are actively attempting to replace this project's functionality with a set of functions that are being added to the operator-sdk (https://sdk.operatorframework.io/docs/olm-integration/cli-overview/) via the newer API project (https://github.com/operator-framework/api/tree/master/pkg/validation). Keep in mind that this is still a work in progress, though my understanding is that within the next week or two we are expecting functional parity with the operator-courier.

**Comment by hassenius** [comment]
Thanks a million @kevinrizza.
I guess then that aiming for using operator-sdk for this as it becomes available will be more strategically appropriate, and I guess if support for operator-courier is fizzling away there's not much point investing in pulling it into our pipeline process.
