### ISSUE TITLE
Courier should be able to create an output json file that contains both WARNINGS and ERRORS

### ISSUE THREAD

**Issue by scoheb** [operator-framework/operator-courier#20]
Courier should accept an argument pointing to a path/file where JSON output should be placed.

The JSON output should contain 2 lists:
- warnings
- errors

It should also provide any additional specific info on each warning/error. For example:
- line number
- etc.

**Comment by kevinrizza** [comment]
This issue was resolved by https://github.com/operator-framework/operator-courier/pull/27
