### ISSUE TITLE
operator-courier push failed: Unauthorized access

### ISSUE THREAD

**Issue by hongkailiu** [operator-framework/operator-courier#30]
I must have missed something.

I created already the app reg. on quay.io. Anything need to be configured there?

```
https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md
(p3env) [hongkliu@MiWiFi-R1CM-srv ~]$ pip show operator-courier
Name: operator-courier
Version: 1.0.2
Summary: Build, verify and push operators
Home-page: https://github.com/operator-framework/operator-courier
Author: AOS Marketplace
Author-email: aos-marketplace@redhat.com
License: UNKNOWN
Location: /home/hongkliu/p3env/lib/python3.7/site-packages
Requires: requests, pyyaml
Required-by: 

$ echo $BUNDLE_DIR
/home/hongkliu/go/src/github.com/hongkailiu/operators/svt-app-operator/deploy/BUNDLE_DIR

$ ll $BUNDLE_DIR
total 24
-rw-rw-r--. 1 hongkliu hongkliu   629 Feb 25 14:35 svt-app-operator.crd.yaml
-rw-rw-r--. 1 hongkliu hongkliu    95 Feb 26 01:17 svt-app-operator.package.yaml
-rw-rw-r--. 1 hongkliu hongkliu 15669 Feb 26 15:20 svt-app-operator.v0.0.2.clusterserviceversion.yaml

$ operator-courier verify $BUNDLE_DIR

$ AUTH_TOKEN=$(curl -sH "Content-Type: application/json" -XPOST https://quay.io/cnr/api/v1/users/login -d '
> {
>     "user": {
>         "username": "'"${QUAY_USERNAME}"'",
>         "password": "'"${QUAY_PASSWORD}"'"
>     }
> }' | jq -r '.token')


$ echo $AUTH_TOKEN
basic ***==

$ EXAMPLE_NAMESPACE=hongkailiu
$ EXAMPLE_REPOSITORY=svt-app-operator
$ EXAMPLE_RELEASE=0.0.2
$ operator-courier push $BUNDLE_DIR $EXAMPLE_NAMESPACE $EXAMPLE_REPOSITORY $EXAMPLE_RELEASE $AUTH_TOKEN
ERROR:operatorcourier.push:{"error":{"code":"forbidden","details":{"package":"hongkailiu/svt-app-operator","scopes":["push"]},"message":"Unauthorized access for: hongkailiu/svt-app-operator"}}

Traceback (most recent call last):
  File "/home/hongkliu/p3env/bin/operator-courier", line 10, in <module>
    sys.exit(main())
  File "/home/hongkliu/p3env/lib/python3.7/site-packages/operatorcourier/cli.py", line 9, in main
    parser.parse()
  File "/home/hongkliu/p3env/lib/python3.7/site-packages/operatorcourier/cli.py", line 36, in parse
    getattr(self, args.command)()
  File "/home/hongkliu/p3env/lib/python3.7/site-packages/operatorcourier/cli.py", line 56, in push
    api.build_verify_and_push(args.namespace, args.repository, args.release, args.token, source_dir=args.source_dir)
  File "/home/hongkliu/p3env/lib/python3.7/site-packages/operatorcourier/api.py", line 73, in build_verify_and_push
    PushCmd().push(temp_dir, namespace, repository, revision, token)
  File "/home/hongkliu/p3env/lib/python3.7/site-packages/operatorcourier/push.py", line 27, in push
    self._push_to_registry(namespace, repository, release, base64_bundle, auth_token)
  File "/home/hongkliu/p3env/lib/python3.7/site-packages/operatorcourier/push.py", line 56, in _push_to_registry
    raise ValueError("Failed to push to app registry: {}".format(msg))
ValueError: Failed to push to app registry: Quay.io answered: 'forbidden' (Unauthorized access for: hongkailiu/svt-app-operator)


```

**Comment by awgreene** [comment]
Hello @hongkailiu, the token is actually a two word string, "basic <some string>", please add quotation marks around the token like so:

```
$ operator-courier push $BUNDLE_DIR $EXAMPLE_NAMESPACE $EXAMPLE_REPOSITORY $EXAMPLE_RELEASE "$AUTH_TOKEN"
```

**Comment by awgreene** [comment]
@kevinrizza Could we add a check to courier that ensures that the token provided isn't equal to "token" and if it is mentions the quotation mark requirement.

**Comment by awgreene** [comment]
@kevinrizza at the very least we should update the command in the [README](https://github.com/operator-framework/operator-courier/blob/master/README.md)

**Comment by awgreene** [comment]
@kevinrizza We could also update the code to get the token:
```
 TOKEN=\"$(curl -sH "Content-Type: application/json" -XPOST https://quay.io/cnr/api/v1/users/login -d '
{
    "user": {
        "username": "'"${QUAY_USERNAME}"'",
        "password": "'"${QUAY_PASSWORD}"'"
    }
}' | jq -r '.token')\"
```

**Comment by kevinrizza** [comment]
@awgreene I would strongly not prefer to update this tool to take plaintext user and password.

Also, having a dependency on the quay.io auth login endpoint is not ideal. Ideally courier could be extended to push to other registries besides quay, and the more dependencies we add to quay apis the harder it gets to migrate later.

I'm not opposed to adding error checking to the auth token -- lots of tools do something similar. We could even have a basic check that tokenizes the auth token and checks that the first string is 'basic' and the second exists and return a readable error if not.

**Comment by awgreene** [comment]
@kevinrizza Where does the plaintext use come in? The only mention I made of the username/password was providing an update to the script to get the token which we already outline in the readme.

The auth token error check is probably a good add.

**Comment by kevinrizza** [comment]
I misunderstood, your suggestion to update the readme is a good one.

**Comment by hongkailiu** [comment]
Yes. It worked.
Thanks for the help @awgreene 
I can see my release on the quay.io UI: https://quay.io/application/hongkailiu/svt-app-operator?tab=releases

I am unblocked now.

**Comment by cmoulliard** [comment]
I followed instructions reported here but I' m geeting a forbidden response

```
AUTH_TOKEN=$(curl -sH "Content-Type: application/json" -XPOST https://quay.io/cnr/api/v1/users/login -d '
cmdsubst quote> {
cmdsubst quote>     "user": {
cmdsubst quote>         "username": "'"cmoulliard+dabou"'",
cmdsubst quote>         "password": "'"H...........F"'"
cmdsubst quote>     }
cmdsubst quote> }' | jq -r '.token')

echo $AUTH_TOKEN
basic Y21vdWxsaWFyZCtkYWJvdTpISkg0N1hXWUU5NEFHNkpPVFRVWEJJRTJSQTlSUUNMRllZVzdQVVZVNEhaV1Q1NjlZQURJSFdRTzI1TFhXWVlG

operator-courier push deploy/olm-catalog cmoulliard component-operator v0.1.0 "$AUTH_TOKEN"
ERROR:operatorcourier.push:{"error":{"code":"forbidden","details":{"package":"cmoulliard/component-operator","scopes":["create"]},"message":"Unauthorized access for: cmoulliard/component-operator"}}

Failed to push to app registry: Quay.io answered: 'forbidden' (Unauthorized access for: cmoulliard/component-operator)
```

**Comment by kevinrizza** [comment]
@cmoulliard Is that a robot account? your robot account may not have push access to the repository you specified without explicitly adding it.

**Comment by cmoulliard** [comment]
This is a robot account. I will have a look

**Comment by cmoulliard** [comment]
The issue with a robot account (which is now the default option as it seems) is that you can only grant admin permissions to repo which already exist and of course the command `operator-courier pus` will only create it

<img width="1396" alt="screenshot 2019-03-08 17 01 14" src="https://user-images.githubusercontent.com/463790/54039738-fe286880-41c3-11e9-927d-7dfd309dfd47.png">

**Comment by cmoulliard** [comment]
I will check if I can use another robot account granted for an org as we can't do that for a user' account

```
I’m trying to use a robot account to create a repository
Robot accounts, despite living under your username or organization name, do not normally possess the ability to create repositories in that namespace for security reasons.

For a user-owned robot account, a repository must be created by the user first, and then permissions granted to the robot account in the repository permissions table to pull and/or push to that repository.

For an organization-owned robot account, a robot account can be granted permission to create repositories if placed under a team with the creator permission. Otherwise, a robot account must be granted individual permissions.
```

**Comment by kevinrizza** [comment]
Yes, the operator-courier is not designed nor intended to do administration of quay namespaces. The fact that a user with permission can push a bundle to a new repository (and by extension create that repository) is an artifact of their api and not a feature specifically intended for the courier. Robot accounts do not have that ability and it is as far as I know by design

**Comment by cmoulliard** [comment]
The command was able to create an application. Is there a way to check if files have been uploaded as cmd output is not verbose ?

```
operator-courier push deploy/olm-catalog ch007m components-operator 0.1.0 "$AUTH_TOKEN" 
WARNING:operatorcourier.validate:csv spec.icon not defined
```

<img width="1411" alt="screenshot 2019-03-08 17 17 14" src="https://user-images.githubusercontent.com/463790/54040647-2f099d00-41c6-11e9-9cf0-e72ef40394ac.png">

**Comment by kevinrizza** [comment]
@cmoulliard the push command will return an error if it failed.

The cli doesn't currently have a way to specify verbose output, but that is something we plan on implementing in the future.

**Comment by kevinrizza** [comment]
@cmoulliard if you want to look from the quay ui, click on releases from that screen and check that the latest release version is listed.

**Comment by cmoulliard** [comment]
release is there : https://quay.io/application/ch007m/components-operator?tab=releases
