### ISSUE TITLE
Consider using JSON schema for validation

### ISSUE THREAD

**Issue by csomh** [operator-framework/operator-courier#39]
YAML can easily be transformed to JSON, and there is [JSON schema](https://json-schema.org/), which can be used to describe how a valid artifact should look like. There is also a [Python package](https://pypi.org/project/jsonschema/) that implements the specification and provides validation.

Would it make sense to follow this path for validating artifacts, instead of writing and testing a lot of validation code? Schema(s) will need testing, but the effort would be much lower.

**Comment by scoheb** [comment]
A nice example of this can be found here: https://pagure.io/fedora-ci/messages/

**Comment by kevinrizza** [comment]
The problem with schema testing is that many layers of edge cases for these bundles. In many cases, it is not simple enough for us to verify that certain fields exist or not and what their types are. We have more complex validation logic that verifies that, if a field exists in one file, that a corresponding field or value exists in another file. For example:

Iterate over the `csv`'s `customresourcedefinitions.owned` list, and for each one ensure that, in the list of `crd` files, ensure that one and exactly one's `metadata.name` matches `customresourcedefinitions.owned.name`

I think that use cases like that can't really be defined by a simple schema validation. @scoheb @csomh please correct me if I am missing or misunderstanding something here.

**Comment by csomh** [comment]
@kevinrizza, yes, you are right that jsonschema might not be able to check such constraints, without some external help. Still, reading through `validate.py` and `const_io.py`, it seems that most of the checks currently done by Operator Courier are actually not of this kind. 

Instead, the code mostly checks if fields are present or have the right type. And implements some ways of reporting validation errors. All these have well tested implementations in jsonschema.

Let me give you an example: `ValidateCmd._pkgs_validation()` could be replaced by the following piece of schema:
```json
{
    "title": "Package manifest", 
    
    "type": "object",
    
    "properties": {
        "packageName": {
            "type": "string",
            "description": "Name of the package"
        },
        "channels": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "currentCSV": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "currentCSV"
                ]
            },
            "minItems": 1,
            "uniqueItems": true
        }
    },
    "required": [
        "packageName",
        "channels"
    ]
}
```

The above schema does not check if `currentCSV` is one of the CSV names, but should be trivial to create a sub-schema for this on the fly.

For me, the schema above is easier to read, understand and reason about than the current Python implementation. Even if some code would be required to check some of the aspects, most things could be covered by simple schema validation.

**Comment by csomh** [comment]
@kevinrizza, I've spent some time trying to rewrite parts of `validate.py` to use schemas, in order to convince you how cool they are :)

But I've hit a complication, which is: currently, some issues are reported as errors, others as warnings. Is there any hard requirement on how these two types are differentiated? Is there any documentation, I could refer to? Why are warnings important and who uses them?

**Comment by kevinrizza** [comment]
@csomh 

Errors in the validator describe things which either make the bundle itself invalid (invalid yaml, missing files) or errors which will prevent OLM from managing the bundle.

Warnings are used to describe problems with the bundle that will not prevent execution. For example, missing metadata fields.
