### ISSUE TITLE
Output the operator bundle when running verify

### ISSUE THREAD

**Issue by dirgim** [operator-framework/operator-courier#76]
Adding an option to locally output the operator bundle to a file when running _verify_ would be a great help when locally testing/deploying the operator.

**Comment by kevinrizza** [comment]
This is something that could be done from the command line with an additional flag added to the `verify` command. We can look into implementing something like this.

**Comment by kevinrizza** [comment]
This issue is resolved by https://github.com/operator-framework/operator-courier/pull/91
