### ISSUE TITLE
ui validation warning causing courier to exit with error code: 1

### ISSUE THREAD

**Issue by scoheb** [operator-framework/operator-courier#84]
(tmp-XVr6zr33) shebert@localhost/tmp/22:$ operator-courier verify .
WARNING:operatorcourier.validate:csv metadata.annotations.certified not defined.
(tmp-XVr6zr33) shebert@localhost/tmp/22:$ echo $?
0
(tmp-XVr6zr33) shebert@localhost/tmp/22:$ 
(tmp-XVr6zr33) shebert@localhost/tmp/22:$ operator-courier verify --ui_validate_io .
WARNING:operatorcourier.validate:csv metadata.annotations.certified not defined.
WARNING:operatorcourier.validate:csv metadata.annotations.repository not defined.Without this field, the link to the operator source code will not be displayed in the UI.
'capability'
(tmp-XVr6zr33) shebert@localhost/tmp/22:$ echo $?
1
(tmp-XVr6zr33) shebert@localhost/tmp/22:$

**Comment by awgreene** [comment]
@galletti94 @kevinrizza @jeremylinlin @MartinBasti 

If ui validation tests are going to fail courier it would seem that the logs should be errors.

**Comment by galletti94** [comment]
Sorry for the inconvenience. There is a known bug in courier involving the capabilities check. PR #67 fixed it and it has been merged but a new release of courier hasn't been cut yet. Once we cut a new release, the `--ui-validate-io` flag will work.

**Comment by SamiSousa** [comment]
Closing due to #67 being merged. Release 1.2.1 is available on PyPI and has this fix
