### ISSUE TITLE
Operator-courier must not require that the quay repo name match the package name in the manifest

### ISSUE THREAD

**Issue by ralphbean** [operator-framework/operator-courier#86]
See a3e0cb2769b3acc049d3fa2f6bec34747aa88e0c.  That requires that the quay repo name we're pushing to matches the package name in the manifests.

This will break the certified-operators partner/ISV workflow.  They push to repo names in quay that have a `uuid` appended on the end.  They do this in order to guarantee that their system only pushes content that corresponds with the correct account.  Of course, with the appended uuid, the quay repo name will never match the package manifest name.

This is a blocker for OMPS to upgrade to the next version of operator courier, which includes another critical change (see #85).

**Comment by ralphbean** [comment]
That change should either be reverted or made optional.

**Comment by kevinrizza** [comment]
@ralphbean This is a requirement for the OpenShift backend. Right now OLM and Marketplace will not work if these two fields do not match, which is why the requirement is here.

**Comment by ralphbean** [comment]
OK - closing this after discussion.  Will file tickets to address this in RHC, OMPS, and COMET.
